<?php

/**
 * Implements hook_menu().
 */
function firstcarousel_menu() {
	$items = array();
	
	$items['node/autocomplete'] = array(
		'title' => 'Node autocomplete',
		'page callback' => 'node_autocomplete',
		'access arguments' => array('access administration pages'),
		'type' => MENU_CALLBACK,
		'file' => 'node.carousel.inc',
	);
	
	$items['node/%node/carousel'] = array(
		'title' => 'Carousel',
		'page callback' => 'node_page_carousel',
		'page arguments' => array(1),
		'access callback' => 'node_access',
		'access arguments' => array('update', 1),
		'weight' => 5,
		'type' => MENU_LOCAL_TASK,
		'context' => MENU_CONTEXT_PAGE,
		'file' => 'node.carousel.inc',
	);

	return $items;
}


/**
 * Implements hook_admin_paths().
 */
function firstcarousel_admin_paths() {
	if (variable_get('node_admin_theme')) {
		$paths = array(
			'node/*/carousel' => TRUE,
		);
		return $paths;
	}
}


/**
 * Implements hook_block_info().
 */
function firstcarousel_block_info() {
	
	$blocks = array();
	
	$blocks['carousel'] = array(
		'info' => 'Firstpage Carousel',
		'cache' => DRUPAL_CACHE_GLOBAL,
	);
	
	return $blocks;
}


/**
 * Implements hook_block_view().
 */
function firstcarousel_block_view($block_name = '') {
	if ($block_name == 'carousel') {
		$module_path = drupal_get_path('module', 'firstcarousel');
		drupal_add_js(drupal_get_path('theme', 'intheme').'/js/jquery.tools.min.js');
		drupal_add_js($module_path.'/firstcarousel.js');
		drupal_add_css($module_path.'/firstcarousel.css');
		
		$limit = variable_get('firstcarousel_block_count', 4);
		
		$query = db_select('node', 'n');
		$query->innerJoin('node_weight', 'nw', 'n.nid = nw.nid');
		$query->fields('n', array('nid'));
		$query->condition('n.status', 1);
		$query->condition('n.type', 'article');
		$query->range(0, $limit);
		$query->orderBy('weight', 'ASC');
		$query->orderBy('created', 'DESC');
	
		$nids = $query->execute()->fetchCol();
		
		$block = array(
			'subject' => '',
			'content' => theme('firstcarousel_block_html', array('nids' => $nids)),
		);
		
		return $block;
	}
}

/**
 * Implements hook_theme().
 */
function firstcarousel_theme($existing, $type, $theme, $path) {
	return array(
		'firstcarousel_block_html' => array(
			'variables' => array(
				'nids' => NULL,
			),
			'template' => 'firstcarousel-block-html',
		),
		'firstcarousel_block_item' => array(
			'variables' => array(
				'node' => NULL,
			),
			'template' => 'firstcarousel-block-item',
		),
		'firstcarousel_order' => array(
			'render element' => 'form',
		),
	);
}

/**
 * Implements hook_preprocess_theme()
 */
function firstcarousel_preprocess_firstcarousel_block_html(&$vars) {
	
	$tabs = array();
	$items = '';
	$nids = $vars['nids'];
	
	foreach ($nids as $nid) {
		$node = node_load($nid);
		
		$tabs[] = truncate_utf8($node->title, '80', FALSE, TRUE, 1);		
		$items .= theme('firstcarousel_block_item', array('node' => $node));
	}
	
	$vars['tabs'] = theme('item_list', array('items' => $tabs, 'attributes' => array('class'=> 'slidetabs')));
	$vars['items'] = $items;
}

function firstcarousel_preprocess_firstcarousel_block_item(&$vars) {
	$node = $vars['node'];
	$lang = $node->language;

	$image = '';
	if (isset($node->field_media[$lang][0])) {
		$file = (object) $node->field_media[$lang][0];
		$fid = $file->fid;
		
		$style_vars = array(
			'path' => file_load($fid)->uri,
			'style_name' => variable_get('firstcarousel_image_style', 'carousel'),
		);
		$image = theme('image_style', $style_vars);
	}
	
	// print_r($style_vars);
	
	$vars['image'] = $image;
	$vars['title'] = $node->title;
	$vars['link'] = url('node/'.$node->nid);
	
	$text = '';
	if (isset($node->field_short[$lang][0]))
		$text = $node->field_short[$lang][0]['safe_value'];
	$vars['text'] = $text;
}

/**
 * Implement hook_block_configure().
 */ 
function firstcarousel_block_configure($delta = '') {
	$form = array();
	
	$form['firstcarousel_block_count'] = array(
		'#type' => 'select', 
		'#title' => t('Number of items to display'), 
		'#default_value' => variable_get('firstcarousel_block_count', 4), 
		'#options' => drupal_map_assoc(array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)),
	);
	
	return $form;
}

/**
 * Implement hook_block_save().
 */
function firstcarousel_block_save($delta = '', $edit = array()) {
	variable_set('firstcarousel_block_count', $edit['firstcarousel_block_count']);
} 

/**
 * Implements hook_image_default_styles().
 */
function firstcarousel_image_default_styles() {

	$styles = array();

	$styles['carousel'] = array(
		'effects' => array(
			array(
				'name' => 'image_scale_and_crop',
				'data' => array(
					'width' => 620,
					'height' => 240,
					'upscale' => 1,
				),
				'weight' => 0,
			),
		),
	);
	
	return $styles;
}

/**
 * Implements hook_image_style_flush().
 *
 */
function firstcarousel_style_flush($style) {
	// The $style parameter is an image style array.

	cache_clear_all('*', 'carousel', TRUE);
}

