<?php


/**
 * Implements hook_theme().
 */
function author_theme($existing, $type, $theme, $path) {
	return array(
		'author_data' => array(
			'variables' => array(
				'uid' => NULL,
			),
			'template' => 'author-data',
		),
	);
}

/**
 * preprocess author.tpl.php
 */
function author_preprocess_author_data(&$vars) {
	
	$author = user_load($vars['uid']);
	
	$vars['name'] = theme('username', array('account' => $author));
	
	$picture_path = ($author->picture) ? $author->picture->uri : drupal_get_path('theme', 'intheme').'/images/noimage.jpg';
		
	$vars['picture'] = theme('image', array('path' => $picture_path, 'width' => 190, 'height' => 200));
	$vars['contact'] = l(t('Contact'), 'user/'.$author->uid.'/contact');
}

/**
 * Implements hook_block_info().
 */
function author_block_info() {
	
	$blocks = array();
	
	$blocks['author'] = array(
		'info' => 'Author',
		'cache' => DRUPAL_NO_CACHE,
	);
	
	return $blocks;
}


/**
 * Implements hook_block_view().
 */
function author_block_view($block_name = '') {
	
	if ($block_name == 'author') {
		if (arg(0) == 'node' && is_numeric(arg(1))) {
			$uid = db_query('SELECT uid FROM {node} WHERE nid = :nid', array(':nid' => arg(1)))->fetchField();
			
			$block = array(
				'subject' => t('Author'),
				'content' => theme('author_data', array('uid' => $uid)),
			);
		
			return $block;
		}
	}
}
