<?php

/**
 * Implements hook_menu().
 */
function live_css_menu() {
  $items = array();

  $items['css/save'] = array(
    'page callback' => 'live_css_save', 
    'access arguments' => array('access content'), 
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Implements hook_init().
 */
function live_css_init() {
  //check permissions
  if (user_access('edit css')) {
    drupal_add_html_head_link(array(
      'id' => 'bespin_base',
      'href' => '/' . drupal_get_path('module', 'live_css') . '/bespin/prebuilt/',
      'rel' => 'bespin_base'
    ));
    drupal_add_css(drupal_get_path('module', 'live_css') . '/bespin/prebuilt/BespinEmbedded.css', 'module', 'all', FALSE);
    drupal_add_js(drupal_get_path('module', 'live_css') . '/bespin/prebuilt/BespinEmbedded.js');
    
    drupal_add_js(drupal_get_path('module', 'live_css') . '/plugins.js');
    
    //load the list of stylesheets
    drupal_add_css(drupal_get_path('module', 'live_css') . '/css.css', 'module', 'all', FALSE);
    drupal_add_js(drupal_get_path('module', 'live_css') . '/css.js');
  }
}

function live_css_permission() {
  return array(
    'edit css' => array(
      'title' => t('Edit and save CSS'),
      'description' => t('Edit and save CSS with the live editor.'),
    )
  );
}

function live_css_save(){
  $css = $_POST['css'];
  $href = $_POST['href'];
  
  //calculate the file path relative to the base drupal folder
  $parts = split('/', $href);
  $path = '';
  for($i = 3; $i < count($parts); $i++){
    $path .= $parts[$i] . '/';
  }
  $path = substr($path, 0, strpos($path, '?'));
  
  //save file back
  $fh = fopen($path, 'w') or die("can't open file");
  fwrite($fh, $css);
  fclose($fh);
  
  echo drupal_json_encode(array(
    'result' => 'success',
    'filename' => $path
  ));
}
