<?php

/**
 * Implements hook_form_alter().
 */
function user_toolbar_form_alter(&$form, &$form_state, $form_id) {

	switch ($form_id) {
		case 'user_login':
		case 'user_register_form':
		case 'user_pass':
			drupal_set_title('');
		break;
	}
}

/**
 * Implements hook_theme().
 */
function user_toolbar_theme() {
	return array(
		'user_toolbar' => array(
			'variables' => array(),
			'template' => 'user-toolbar',
		),
	);
}

/**
 * theme: user_toolbar preprocess
 */
function template_preprocess_user_toolbar(&$vars) {
	global $user;

	$items[] = array(
		'data' => l(t('email'), 'contact'),
		'class' => array('contact-link'),
	);
	
	$items[] = array (
		'data' => '<span>'.t('seguici su').'</span>'.
			'<a class="tw-page" href="http://twitter.com/interno18" title="twitter" target="_blank"></a>'.
			'<a class="fb-page" href="http://www.facebook.com/pages/interno18it/179744205406067" title="facebook" target="_blank"></a>'.
			'<a class="rss-page" href="'.url('feed', array('absolute'=>TRUE)).'" title="RSS" target="_blank"></a>'.
			'<a class="yt-page" href="http://www.youtube.com/user/interno18video" title="youtube" target="_blank"></a>',
		'class' => array('social-links'),
	);
	
	if ($user->uid > 0) { // logged user
		$items[] = array (
			'data' => l('', 'user/logout', array('attributes' => array('class' => array('logout-link')))),
		);
	}
	else { // anonymous
		$items[] = array(
			'data' => l('', 'user', array('attributes' => array('class' => array('login-link')))),
		);
	}
	
	$vars['toolbar_links'] = theme('item_list', array('items' => $items));

	if (module_exists('gsearch'))
		$vars['google_search'] = theme('gsearch_form');
	
}
